version: "3"

services:
  backend:
    image: ${DOCKER_IMAGE}
    container_name: athens-backend
    ports:
      - 8080:8080
    env_file: .env
    volumes:
      - ./log:/log
    restart: always
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: athens-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always

volumes:
  redis-data:
