services:
  backend-green:
    extends:
      file: docker-compose.yml
      service: backend
    container_name: athens-green
    ports:
      - 8082:8080
    networks:
      - ubuntu_app-network
  redis:
    extends:
      file: docker-compose.yml
      service: redis
    ports: [ ]  # 포트 매핑 제거

networks:
  ubuntu_app-network:
    external: true
