version: "3"

services:
  backend-green:
    extends:
      file: docker-compose.yml
      service: backend
    container_name: athens-green
    ports:
      - 8082:8080
    networks:
      - ubuntu_app-network

networks:
  ubuntu_app-network:
    external: true
