version: "3"

services:
  backend-green:
    image: ${DOCKER_IMAGE}
    container_name: athens-green
    ports:
      - 8082:8080
    env_file: .env
    volumes:
      - ./log:/log
    restart: always
