services:
  redis:
    image: redis:latest
    container_name: athens-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - ubuntu_app-network

networks:
  ubuntu_app-network:
    external: true

volumes:
  redis-data:
