version: "3"

services:
  backend-blue:
    extends:
      file: docker-compose.yml
      service: backend
    container_name: athens-blue
    ports:
      - 8081:8080
    networks:
      - app-network

networks:
  app-network:
    external: true
