services:
  backend-green:
    image: ${DOCKER_IMAGE}
    container_name: athens-green
    env_file: .env
    volumes:
      - ./log:/log
    ports:
      - 8082:8080
    restart: always
    depends_on:
      - redis
    networks:
      - ubuntu_app-network

networks:
  ubuntu_app-network:
    external: true
